---
- name: Generate random password
  local_action: shell pwgen -s1
  register: user_pw

- name: Set password for root
  user:
    name: root
    update_password: always
    password: "{{ user_pw.stdout | password_hash('sha512') }}"

- name: Print password
  debug:
    msg: "Server: {{ ansible_eth0.ipv4.address }} - {{ user_pw.stdout }}   "
