---
- hosts: all
  vars:
    server: "{{ ansible_eth0.ipv4.address }}"
  tasks:
    - include_tasks: tasks/centos-enable-epal.yml
    - include_tasks: tasks/check-iptables.yml
    - include_tasks: tasks/centos-update.yml
    - include_tasks: tasks/change-password.yml
